Add ability to run JmxScraper over ssl
Also adds ability to auto-detect jmxHost, jmxPort, jmxSSL, etc

diff --git a/ds-collector/ds-collector b/ds-collector/ds-collector
--- a/ds-collector/ds-collector
+++ b/ds-collector/ds-collector
@@ -104,36 +104,14 @@ connection_tests() {
 # shellcheck disable=SC2086
 list_cassandra_nodes() {
   statusState=0
-  # change this if there's an alias, or a full path needs to be specified
-  nodetoolCmd="nodetool"
-  # Check if adding password to nodetool is needed:
-  nodetoolCredentials=""
-  if [[ -n ${jmxUsername} ]] && [[ -n ${jmxPassword} ]]
-  then
-    nodetoolCredentials="-u $jmxUsername -pw $jmxPassword"
-  fi
-  jmxOpts=""
-  if [ "$jmxSSL" = "true" ]; then
-    jmxOpts="--ssl"
-  fi
 
   # 'timeout -t SECS' is required on older busybox
   TIMEOUT_OPT="3"
   ( timeout --help | grep -q "t SECS" ) && TIMEOUT_OPT="-t 3"
   timeout_command="timeout $FOREGROUND_OPT $TIMEOUT_OPT"
 
-  jmxHost='127.0.0.1'
-  $timeout_command nc -zv localhost $jmxPort > /dev/null 2>&1
-  if [ $? = 0 ]; then
-    jmxHost='localhost'
-    echo "Using localhost to connect to JMX..."
-  else
-    $timeout_command nc -zv $(hostname) $jmxPort > /dev/null 2>&1
-    if [ $? = 0 ]; then
-      jmxHost="$(hostname)"
-      echo "Using $(hostname) to connect to JMX..."
-    fi
-  fi
+  discover_jmx
+
   cmd="set -o pipefail ; ${nodetoolCmd} -h $jmxHost -p $jmxPort ${jmxOpts} $nodetoolCredentials status | grep UN | tr -s ' ' | cut -d' ' -f2"
   cassandraNodes=$(node_connect "$cmd" | tr "\n\r" " ")
   statusState=$?
@@ -479,11 +457,13 @@ collect_via_rust() {
   export skipSudo="${skipSudo:-false}"
   export skip_dse="${skip_dse:-false}"
   export prometheus_jar="${baseDir}/${prometheus}"
+  export jmxHost
   export jmxPort
   export jmxUsername
   export jmxPassword
   export jmxSSL
-  export jmxHost
+  export jmxPlain="$(if [ "${jmxSSL}" = "true" ]; then echo "false"; else echo "true"; fi)"
+  export jmx_exporter_opts
   export nodetoolCredentials
   export cqlsh_host="${cqlsh_host:-$(hostname)}"
   export cqlsh_port="${cqlsh_port:-9042}"
@@ -599,6 +579,9 @@ collect_info_setup() {
   update_path
   update_env
 
+  server_cmdline="$(ps -aef|grep -e "org.apache.cassandra.service.CassandraDaemon" -e "com.datastax.bdp.DseModule"|grep java)"
+  server_pid="$(echo ${server_cmdline}|sed -e 's|^[ ]*[^ ]*[ ]*\([^ ]*\)[ ].*|\1|')"
+
   cqlshOpts="${cqlshOpts} --username=$cqlshUsername --password=$cqlshPassword"
   if [ "$cqlshSSL" != "false" ]; then
     echo "enabling ssl for cqlsh"
@@ -613,32 +596,7 @@ collect_info_setup() {
   ( timeout --help | grep -q "t SECS" ) && TIMEOUT_OPT="-t 30"
   timeout_command="timeout $FOREGROUND_OPT $TIMEOUT_OPT"
 
-  # Make our best guess on the host address to use to access nodetool/JMX
-  jmxHost='127.0.0.1'
-  $timeout_command nc -zv localhost $jmxPort > /dev/null 2>&1
-  if [ $? == 0 ]; then
-    jmxHost='localhost'
-    echo "Using localhost to connect to JMX..."
-  else
-    $timeout_command nc -zv $(hostname) $jmxPort > /dev/null 2>&1
-    if [ $? == 0 ]; then
-      jmxHost="$(hostname)"
-      echo "Using $(hostname) to connect to JMX..."
-    fi
-  fi
-
-  # Check if adding password to nodetool is needed:
-  nodetoolCredentials=""
-  if [[ -n ${jmxUsername} ]] && [[ -n ${jmxPassword} ]]
-  then
-    nodetoolCredentials="-u $jmxUsername -pw $jmxPassword"
-  fi
-
-  server_pid="$(ps -aef|grep org.apache.cassandra.service.CassandraDaemon|grep java|sed -e 's|^[ ]*[^ ]*[ ]*\([^ ]*\)[ ].*|\1|')"
-  if [ -z "$server_pid" ] ; then
-    # no Cassandra server found, look for DSE
-    server_pid="$(ps -aef|grep com.datastax.bdp.DseModule|grep java|sed -e 's|^[ ]*[^ ]*[ ]*\([^ ]*\)[ ].*|\1|')"
-  fi
+  discover_jmx
 
   # DSE
   if [ "$is_dse" == "true" ]; then
@@ -720,6 +678,80 @@ collect_dse_solr_cores() {
             $timeout_command $dse_bin_dir/dsetool $dt_opts list_index_files "$core" > "$artifactDir/solr/$core/index_files" 2>&1
         done
     fi
+}
+
+discover_jmx() {
+ jmxPort="7199"
+ jmxHost="127.0.0.1"
+ tmp=""
+
+  # XXX from Cassandra 4.0 it is possible to have multiple process per ip, how can we handle this?
+  server_cmdline="$(ps -aef|grep -e "org.apache.cassandra.service.CassandraDaemon" -e "com.datastax.bdp.DseModule"|grep java)"
+
+  tmp=$(echo "${server_cmdline}" | grep 'cassandra.jmx.local.port=' |sed -e 's|^.*-Dcassandra.jmx.local.port=\([^ ]*\).*$|\1|')
+  if [ -n "$tmp" ]; then
+      jmxPort="$tmp"
+  else
+      tmp=$(echo "${server_cmdline}" | grep 'cassandra.jmx.remote.port=' |sed -e 's|^.*-Dcassandra.jmx.remote.port=\([^ ]*\).*$|\1|')
+      if [ -n "$tmp" ]; then
+          jmxPort="$tmp"
+      fi
+      tmp=$(echo "${server_cmdline}" | grep 'java.rmi.server.hostname=' |sed -e 's|^.*-Djava.rmi.server.hostname=\([^ ]*\).*$|\1|')
+      if [ -n "$tmp" ]; then
+          jmxHost="$tmp"
+      fi
+  fi
+  # test jmxHost, failling back if need be
+  $timeout_command  nc -zv "${jmxHost}" "${jmxPort}" > /dev/null 2>&1
+  if [ $? != 0 ]; then
+    $timeout_command nc -zv localhost $jmxPort > /dev/null 2>&1
+    if [ $? = 0 ]; then
+      jmxHost='localhost'
+    else
+      $timeout_command nc -zv $(hostname) $jmxPort > /dev/null 2>&1
+      if [ $? = 0 ]; then
+        jmxHost="$(hostname)"
+      fi
+    fi
+  fi
+  $timeout_command  nc -zv "${jmxHost}" "${jmxPort}" > /dev/null 2>&1
+  if [ $? = 0 ]; then
+    echo "Using ${jmxHost}:${jmxPort} to connect to JMX..."
+  else
+    echo "JMX isn't available at ${jmxHost}:${jmxPort}"
+  fi
+
+  # Check if adding password to nodetool is needed:
+  nodetoolCredentials=""
+  if [[ -n ${jmxUsername} ]] && [[ -n ${jmxPassword} ]] ; then
+    nodetoolCredentials="-u $jmxUsername -pw $jmxPassword"
+  elif echo "${server_cmdline}" | grep -q 'com.sun.management.jmxremote.authenticate=true' ; then
+    echo "JMX authentication is enabled but no credentials have been configured. Please configure jmxUsername and jmxPassword in collector.conf"
+  fi
+  jmxOpts=""
+  jmx_exporter_opts=""
+  if [ "$jmxSSL" = "true" ] || echo "${server_cmdline}" | grep -q 'com.sun.management.jmxremote.ssl=true' ; then
+    jmxSSL="true"
+    jmxOpts="--ssl"
+
+    tmp=$(echo "${server_cmdline}" | grep 'javax.net.ssl.keyStore=' |sed -e 's|^.*-Djavax.net.ssl.keyStore=\([^ ]*\).*$|\1|')
+    if [ -n "$tmp" ]; then
+        jmx_exporter_opts="${jmx_exporter_opts} -Djavax.net.ssl.keyStore=${tmp}"
+    fi
+    tmp=$(echo "${server_cmdline}" | grep 'javax.net.ssl.keyStorePassword=' |sed -e 's|^.*-Djavax.net.ssl.keyStorePassword=\([^ ]*\).*$|\1|')
+    if [ -n "$tmp" ]; then
+        jmx_exporter_opts="${jmx_exporter_opts} -Djavax.net.ssl.keyStorePassword=${tmp}"
+    fi
+    tmp=$(echo "${server_cmdline}" | grep 'javax.net.ssl.trustStore=' |sed -e 's|^.*-Djavax.net.ssl.trustStore=\([^ ]*\).*$|\1|')
+    if [ -n "$tmp" ]; then
+        jmx_exporter_opts="${jmx_exporter_opts} -Djavax.net.ssl.trustStore=${tmp}"
+    fi
+    tmp=$(echo "${server_cmdline}" | grep 'javax.net.ssl.trustStorePassword=' |sed -e 's|^.*-Djavax.net.ssl.trustStorePassword=\([^ ]*\).*$|\1|')
+    if [ -n "$tmp" ]; then
+        jmx_exporter_opts="${jmx_exporter_opts} -Djavax.net.ssl.trustStorePassword=${tmp}"
+    fi
+  fi
+  dt_opts="-h ${jmxHost} -p ${jmxPort} ${nodetoolCredentials} ${jmxOpts} ${dt_opts}"
 }
 
 archive_artifacts() {
@@ -979,7 +1011,7 @@ FOREGROUND_OPT="--foreground"
 # It's built from the jmx_exporter/collector
 # it used to be a standalone tool
 
-prometheus="collector-0.11.1-SNAPSHOT.jar"
+prometheus="collector-0.16.2-SNAPSHOT.jar"
 
 dstat="dstat"
 
@@ -1001,9 +1033,6 @@ sshOptionConnectAttempts="true"
 # k8s
 k8s_namespace="default"
 
-# JMX port
-jmxPort="7199"
-
 # s3
 bucket="collector-dead-drop"
 #useS3Auth="true"
@@ -1011,6 +1040,8 @@ bucket="collector-dead-drop"
 cqlshUsername="cassandra"
 cqlshPassword="cassandra"
 cqlshSSL="false"
+
+nodetoolCmd="nodetool"
 
 # initialize arrays
 myArrays=(
@@ -1038,7 +1069,6 @@ myVariables=(
   sshIdentity
   enablePingTest
   userName
-  skipStat
   skipSudo
   testMode
   executeMode
